# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 11:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height_field', max_length=255, upload_to='image/%Y/%m/', width_field='width_field')),
                ('height_field', models.PositiveSmallIntegerField()),
                ('width_field', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_auth.UserProfileImage'),
        ),
    ]
